pragma solidity ^0.4.24;

contract RealEstate {

    // state variables in contracts are
    // written to disk on the blockchain,
    // are not just stored in memory
    address public seller;
    address public buyer;
    string public streetAddress;
    string title;
    uint256 public price;

    constructor() public {
        // Who is the seller?
        seller = msg.sender;
        // What is the street address
        streetAddress = "350 5th Ave, New York, NY 10118";
        // What is the title?
        // random string (digest from 'myhouse') generated by http://www.convertstring.com/Hash/SHA256
        title = "D6D25D54DC11330193D79703B6418D2109F1520BF201BE9A9EDEC26925E13A20";
        // What is the price?
        price = 99 ether; // 99000000000000000000 wei
    }

    // payable modifier implies that this
    // function will be able to send ether
    function buyHouse() payable public {
        // 'safe guards'
        require(seller != 0x0);
        require(buyer == 0x0);
        require(msg.sender != seller);
        require(msg.value == price);
        // buy will be the account that
        // invoke this function
        buyer = msg.sender;
        // send money to the seller address
        seller.transfer(msg.value); // all values in contracts are in Wei unless specifically specified
    }

}
